// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATQCx6YJks1AXi08tDhiJoO8ZNmu5t2Lg',
    appId: '1:917020972935:web:b42725420b001b7fa76522',
    messagingSenderId: '917020972935',
    projectId: 'myhome-dee6b',
    authDomain: 'myhome-dee6b.firebaseapp.com',
    storageBucket: 'myhome-dee6b.appspot.com',
    measurementId: 'G-J43C671503',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBke8BQbSDKzuKUHrdzbuYQxDVgRLXtXxg',
    appId: '1:917020972935:android:bd633042afb581bea76522',
    messagingSenderId: '917020972935',
    projectId: 'myhome-dee6b',
    storageBucket: 'myhome-dee6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaMFk8l02bjPgBebhGIRz9zmCdZXYkwuY',
    appId: '1:917020972935:ios:a9d4162b04d2e30ba76522',
    messagingSenderId: '917020972935',
    projectId: 'myhome-dee6b',
    storageBucket: 'myhome-dee6b.appspot.com',
    iosBundleId: 'com.example.myHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaMFk8l02bjPgBebhGIRz9zmCdZXYkwuY',
    appId: '1:917020972935:ios:a9d4162b04d2e30ba76522',
    messagingSenderId: '917020972935',
    projectId: 'myhome-dee6b',
    storageBucket: 'myhome-dee6b.appspot.com',
    iosBundleId: 'com.example.myHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATQCx6YJks1AXi08tDhiJoO8ZNmu5t2Lg',
    appId: '1:917020972935:web:79e1a21592b246bca76522',
    messagingSenderId: '917020972935',
    projectId: 'myhome-dee6b',
    authDomain: 'myhome-dee6b.firebaseapp.com',
    storageBucket: 'myhome-dee6b.appspot.com',
    measurementId: 'G-T44CSLELZL',
  );

}